
--WEBSHOPUSER
CREATE TABLE WEBSHOPUSER (LOGIN_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ADDRESS_FK_ID INT NOT NULL REFERENCES USERADDRESS (ADDRESS_ID), 
USER_NAME VARCHAR(45) NOT NULL, 
PASSWORD VARCHAR(45) NOT NULL,
EMAIL_ID VARCHAR(45) NOT NULL,
USER_ROLE VARCHAR(45) NOT NULL
)

 CREATE TABLE USERADDRESS(ADDRESS_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
 HOUSE_NO INT NOT NULL,
 STREET VARCHAR(90) NOT NULL, 
 CITY VARCHAR(90) NOT NULL,
 STATE_FK INT NOT NULL REFERENCES STATES (STATE_ID),
 COUNTRY VARCHAR(90) NOT NULL
 )

--CATEGORY
 CREATE TABLE CATEGORY (CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
CATEGORY_NAME VARCHAR(45) NOT NULL, 
CATEGORY_DESCRIPTION VARCHAR(45) NOT NULL,
CATEGORY_IMAGE_PATH VARCHAR(255))

--PRODUCT
 CREATE TABLE PRODUCT (PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
 CATEGORY_FK_ID INT NOT NULL REFERENCES CATEGORY (CATEGORY_ID),
PRODUCT_NAME VARCHAR(45) NOT NULL, 
PRODUCT_DESCRIPTION VARCHAR(45) NOT NULL,
PRODUCT_IMAGE_PATH VARCHAR(255),
PRODUCT_PRICE INT NOT NULL,
PRODUCT_STATUS VARCHAR(45),
PRODUCT_ADDED_DATE TIMESTAMP)

--USERCART
 CREATE TABLE USERCART (CART_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
 PRODUCT_FK_ID INT NOT NULL REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
 USER_FK_ID INT NOT NULL REFERENCES WEBSHOPUSER (LOGIN_ID),
PRODUCT_QUANTITY INT NOT NULL,
TOTAL_PRICE INT NOT NULL,
CART_STATUS VARCHAR(45),
CART_CREATED_DATE TIMESTAMP)

--USERORDER
 CREATE TABLE USERORDER (ORDER_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
USER_FK_ID INT NOT NULL REFERENCES WEBSHOPUSER (LOGIN_ID),
ORDER_NUMBER INT NOT NULL,
ORDER_PRICE INT NOT NULL,
ORDER_DATE TIMESTAMP,
DELIVERY_DATE TIMESTAMP,
ORDER_STATUS VARCHAR(45))

 CREATE TABLE ORDERDETAIL (ORDER_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, 
ORDER_FK_ID INT NOT NULL REFERENCES USERORDER (ORDER_ID),
PRODUCT_FK_ID INT NOT NULL REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
PRODUCT_QUANTITY INT NOT NULL,
TOTAL_PRICE INT NOT NULL
)

select * from usercart
select * from userorder
select * from orderdetail

delete from usercart
delete from orderdetail
delete from userorder

 